name: Generate Profile Visuals

on:
  workflow_dispatch:
  schedule:
    - cron: "17 0 * * *"
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  snake:
    name: Generate contribution snake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: dineshtimilsena0
          outputs: |
            dist/github-snake.svg?palette=github-light
            dist/github-snake-dark.svg?palette=github-dark

      - name: Publish generated assets
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
